### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by ghost** [BasicCode/STM32MP135_Dev_Board_Buildroot#1]
I used the same development board as yours, and used STM32MP135_Dev_Board_Buildroot to build. May I ask if you will have the following errors
[error.txt](https://github.com/BasicCode/STM32MP135_Dev_Board_Buildroot/files/15162099/error.txt)

**Comment by BasicCode** [comment]
I did have a similar error when there was a problem with my card detect pin (I was hand-soldering the connector). Double check if the CD pin is connected properly, or you could try adding the "**broken-cd**" property to the **sdmmc1** node in the device tree [here](https://github.com/BasicCode/STM32MP135_Dev_Board_Buildroot/blob/ec1c58c837043842fff3561ee7889b295165362a/board/stm32mp135_dev_board/stm32mp135_dev_board.dts#L537).

https://wiki.st.com/stm32mpu/wiki/SDMMC_device_tree_configuration
